<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <PropertyGroup>
    <UseSharedCompilation>true</UseSharedCompilation>

    <BuildInParallel>true</BuildInParallel>
    <RestoreDisableParallel>false</RestoreDisableParallel>
  </PropertyGroup>

  <PropertyGroup>
    <AddTransitiveProjectReferencesInStaticGraph>true</AddTransitiveProjectReferencesInStaticGraph>

    <RestoreUseStaticGraphEvaluation>true</RestoreUseStaticGraphEvaluation>
    <RestoreUseLegacyDependencyResolver>false</RestoreUseLegacyDependencyResolver>
  </PropertyGroup>

  <PropertyGroup>
    <RootNamespace>$(MSBuildProjectName)</RootNamespace>
    <ImplicitUsings>disable</ImplicitUsings>

    <Nullable>enable</Nullable>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
  </PropertyGroup>

  <PropertyGroup>
    <Version>1.0.0</Version>
  </PropertyGroup>
</Project>
