<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <StartupObject>$(RootNamespace).Program</StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NLog.Web.AspNetCore">
      <PrivateAssets>compile;contentfiles;analyzers;build</PrivateAssets>
    </PackageReference>

    <ProjectReference Include="../DataAccess/DataAccess.csproj">
      <PrivateAssets>compile;contentfiles;analyzers;build</PrivateAssets>
    </ProjectReference>
  </ItemGroup>
</Project>
