<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <StartupObject>$(RootNamespace).Program</StartupObject>
    <UserSecretsId>45d40908-1b04-40d0-ae74-ce54197ca00f</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NLog.Web.AspNetCore">
      <PrivateAssets>compile;contentfiles;analyzers;build</PrivateAssets>
    </PackageReference>
  </ItemGroup>
</Project>
